apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: shelf
  namespace: argocd

spec:
  sourceRepos:
    - https://github.com/slavasuhoveev/shelf-deployment.git

  destinations:
    - server: https://kubernetes.default.svc
      namespace: shelf-dev

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
