apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shelfFront.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.shelfFront.name }}
  ports:
    - port: {{ .Values.shelfFront.service.port }}
      targetPort: {{ .Values.shelfFront.service.port }}
