apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shelfAuth.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.shelfAuth.name }}
  ports:
    - port: {{ .Values.shelfAuth.service.port }}
      targetPort: {{ .Values.shelfAuth.service.port }}
