apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shelfApi.name }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app.kubernetes.io/name: {{ .Values.shelfApi.name }}
  ports:
    - port: {{ .Values.shelfApi.service.port }}
      targetPort: {{ .Values.shelfApi.service.port }}
