{{- if .Values.shelfApiDb.enabled }}

apiVersion: v1
kind: Service

metadata:
  name: {{ .Values.shelfApiDb.name }}
  namespace: {{ .Values.global.namespace }}

spec:
  selector:
    app.kubernetes.io/name: {{ .Values.shelfApiDb.name }}

  ports:
    - name: postgres
      port: {{ .Values.shelfApiDb.service.port }}
      targetPort: {{ .Values.shelfApiDb.service.port }}
{{- end }}
