# charts/shelf-app/values.yaml

global:
  namespace: default

shelfAuth:
  name: shelf-auth
  image:
    repository: ghcr.io/slavasuhoveev/shelf-auth
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  env:
    ENV: dev
    HTTP_ADDR: ":8080"
    LOG_LEVEL: debug

    JWT_ALG: RS256
    JWT_ISS: shelf-auth
    JWT_AUD: shelf-api

    ACCESS_TTL: 15m
    JWKS_MAX_AGE: 300s

    KEYS_DIR: /run/secrets/keys
    SIGNING_KEY_KID: k1-2025-08-30

    DATABASE_URL: postgres://shelf:shelf@shelf-auth-db:5432/shelf_db?sslmode=disable

    CORS_ORIGINS: http://localhost:3000

    COOKIE_SECURE: "false"
    COOKIE_SAMESITE: Lax
    COOKIE_DOMAIN: ""
  service:
    port: 8080
  probes:
    readiness:
      path: /readyz
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      path: /healthz
      initialDelaySeconds: 15
      periodSeconds: 20
  migration:
    enabled: true
    databaseUrl: postgres://shelf:shelf@shelf-auth-db:5432/shelf_db?sslmode=disable

shelfAuthDb:
  name: shelf-auth-db

  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent

  service:
    port: 5432

  storage:
    size: 1Gi

  env:
    POSTGRES_USER: shelf
    POSTGRES_PASSWORD: shelf
    POSTGRES_DB: shelf_db

shelfApi:
  name: shelf-api
  image:
    repository: ghcr.io/slavasuhoveev/shelf-api
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  env:
    AUTH_JWKS_URL: http://shelf-auth:8080/.well-known/jwks.json

    JWT_ISSUER: shelf-auth
    JWT_AUDIENCE: shelf-api
    JWKS_CACHE_TTL_SECONDS: 300

    POSTGRES_USER: shelf
    POSTGRES_PASSWORD: shelf
    POSTGRES_DB: shelf_db
    POSTGRES_HOST: shelf-api-db
    POSTGRES_PORT: 5432
  service:
    port: 8082
  probes:
    readiness:
      path: /system/readyz
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      path: /system/healthz
      initialDelaySeconds: 15
      periodSeconds: 20
  migration:
    enabled: true

shelfApiDb:
  name: shelf-api-db

  image:
    repository: postgres
    tag: 16-alpine
    pullPolicy: IfNotPresent

  service:
    port: 5432

  storage:
    size: 1Gi

  env:
    POSTGRES_USER: shelf
    POSTGRES_PASSWORD: shelf
    POSTGRES_DB: shelf_db

shelfFront:
  name: shelf-front
  image:
    repository: ghcr.io/slavasuhoveev/shelf-front
    tag: latest
    pullPolicy: Always
  replicaCount: 1
  service:
    port: 3000
  probes:
    readiness:
      path: /readyz
      initialDelaySeconds: 5
      periodSeconds: 10
    liveness:
      path: /healthz
      initialDelaySeconds: 15
      periodSeconds: 20

ingress:
  enabled: true
  className: nginx

  frontHost: front.shelf.local
  authHost: auth.shelf.local
  apiHost: api.shelf.local
