# charts/shelf-app/values.yaml

shelfAuth:
  name: shelf-auth
  image:
    repository: ghcr.io/slavasuhoveev/shelf-auth
    tag: local
  replicaCount: 1
  service:
    port: 8080

shelfApi:
  name: shelf-api
  image:
    repository: ghcr.io/slavasuhoveev/shelf-api
    tag: local
  replicaCount: 1
  service:
    port: 8082

shelfFront:
  name: shelf-front
  image:
    repository: ghcr.io/slavasuhoveev/shelf-front
    tag: local
  replicaCount: 1
  service:
    port: 3000
